name: Run Test Manually

on:
  workflow_dispatch:
    inputs:
      tag_or_file:
        description: "Tag or test file to run"
        required: true

permissions: write-all

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          xvfb-run --auto-servernum npm run tag ${{ inputs.tag_or_file }}
        env:
          DISPLAY: ":99"

      - name: Generate allure report
        if: always()
        run: npm run generate-allure

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 10

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout `gh-pages` Branch (Clean)
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Delete Old Report History (Prevent Repo Growth)
        run: |
          rm -rf gh-pages/*
          mkdir -p gh-pages

      - name: Download Allure Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: gh-pages

      - name: Commit and Push New Allure Report
        run: |
          cd gh-pages
          git config --global user.name "rlln-istarx"
          git config --global user.email "rallen.estrella@istar-x.com"
          git add .
          git commit -m "Update Allure Report - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push --force origin gh-pages
